### ISSUE TITLE
SimpleReport.run

### ISSUE THREAD

**Issue by lgagne413** [deschman/reporting#2]
I reccommend the bolMulti parameter default be False.  In the future, a feature could be added that switches automatically if multi threading fails.  My test seemed to show multiple queries getting in each others way with multi threading on.

**Comment by lgagne413** [comment]
2020-11-23 15:27:30,279 MainThread INFO: Starting report with existing log located at 'C:\Users\lgagne\.spyder-py3\log.txt'
2020-11-23 15:27:30,289 MainThread DEBUG: Variables: selfDir: 'C:\Users\lgagne\.spyder-py3', dirLog: 'C:\Users\lgagne\.spyder-py3\log.txt', dirConfig: 'C:\Users\lgagne\Documents\GitHub\reporting\templates\config.txt'
2020-11-23 15:27:30,290 MainThread DEBUG: Checking for backup files
2020-11-23 15:27:30,291 MainThread DEBUG: No backup found
2020-11-23 15:27:30,291 MainThread DEBUG: Adding row to metadata with:
                         strName: testQuery
                         strSQL: SELECT * FROM PBM_Mart.dbo.DrugGPI
                         strDbType: sqlolap1
                         objCnxn: <pyodbc.Connection object at 0x000001FCE88FAED0>
                         dirDb: 
2020-11-23 15:27:30,294 MainThread DEBUG: Adding row to metadata with:
                         strName: testQuery2
                         strSQL: SELECT * FROM PBM_Mart.ContractInfo.CostBasis
                         strDbType: sqlolap1
                         objCnxn: <pyodbc.Connection object at 0x000001FCE88FAED0>
                         dirDb: 
2020-11-23 15:27:30,298 MainThread INFO: Running with multithreading
2020-11-23 15:27:30,324 Thread-10 DEBUG: Querying database
2020-11-23 15:27:30,325 Thread-11 DEBUG: Querying database
2020-11-23 15:27:30,659 MainThread DEBUG: ['  File "C:\\Users\\lgagne\\Anaconda3\\lib\\runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\spyder_kernels\\console\\__main__.py", line 11, in <module>\n    start.main()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\spyder_kernels\\console\\start.py", line 318, in main\n    kernel.start()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py", line 583, in start\n    self.io_loop.start()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py", line 153, in start\n    self.asyncio_loop.run_forever()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\asyncio\\base_events.py", line 538, in run_forever\n    self._run_once()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\asyncio\\base_events.py", line 1782, in _run_once\n    handle._run()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\asyncio\\events.py", line 88, in _run\n    self._context.run(self._callback, *self._args)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py", line 743, in _run_callback\n    ret = callback()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\gen.py", line 787, in inner\n    self.run()\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\gen.py", line 748, in run\n    yielded = self.gen.send(value)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py", line 361, in process_one\n    yield gen.maybe_future(dispatch(*args))\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\gen.py", line 209, in wrapper\n    yielded = next(result)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py", line 268, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\gen.py", line 209, in wrapper\n    yielded = next(result)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py", line 541, in execute_request\n    user_expressions, allow_stdin,\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\tornado\\gen.py", line 209, in wrapper\n    yielded = next(result)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py", line 300, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py", line 2858, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py", line 2886, in _run_cell\n    return runner(coro)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py", line 68, in _pseudo_sync_runner\n    coro.send(None)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py", line 3063, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py", line 3254, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py", line 3331, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File "<ipython-input-10-faf05b2f0420>", line 1, in <module>\n    runfile(\'C:/Users/lgagne/.spyder-py3/temp.py\', wdir=\'C:/Users/lgagne/Documents/GitHub\')\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\spyder_kernels\\customize\\spydercustomize.py", line 476, in runfile\n    exec_code(file_code, filename, ns_globals, ns_locals)\n', '  File "C:\\Users\\lgagne\\Anaconda3\\lib\\site-packages\\spyder_kernels\\customize\\spydercustomize.py", line 377, in exec_code\n    exec(compile(code, filename, \'exec\'), ns_globals, ns_locals)\n', '  File "C:\\Users\\lgagne\\.spyder-py3\\temp.py", line 20, in <module>\n    rep.run()\n', '  File "C:\\Users\\lgagne\\Documents\\GitHub\\reporting\\templates\\simple.py", line 283, in run\n    self.log(tb_format_stack(), \'DEBUG\')\n']
2020-11-23 15:27:30,659 MainThread CRITICAL: See log for debug details
Traceback (most recent call last):
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
pyodbc.Error: ('HY000', '[HY000] [Microsoft][SQL Server Native Client 11.0]Connection is busy with results for another command (0) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lgagne\Documents\GitHub\reporting\templates\simple.py", line 265, in run
    lstDirs = _procQueries(lstDirs, bolMulti)
  File "C:\Users\lgagne\Documents\GitHub\reporting\templates\simple.py", line 252, in _procQueries
    lstDirs = list(dlyEvent.compute())
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\threaded.py", line 84, in get
    **kwargs
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)
  File "C:\Users\lgagne\Documents\GitHub\reporting\templates\__init__.py", line 371, in getData
    dfTemp = pd.read_sql(strSQL, objCnxn)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\pandas\io\sql.py", line 412, in read_sql
    chunksize=chunksize,
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "C:\Users\lgagne\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * FROM PBM_Mart.ContractInfo.CostBasis': ('HY000', '[HY000] [Microsoft][SQL Server Native Client 11.0]Connection is busy with results for another command (0) (SQLExecDirectW)')
2020-11-23 15:27:30,664 MainThread WARNING: Backing up data
2020-11-23 15:27:30,665 MainThread DEBUG: Backup location: C:\Users\lgagne\.spyder-py3\_backup
2020-11-23 15:27:30,665 MainThread DEBUG: Backing up metadata to 'C:\Users\lgagne\.spyder-py3\_backup\__Metadata.xlsx'
2020-11-23 15:27:30,718 MainThread INFO: Backup successful
2020-11-23 15:27:48,478 MainThread INFO: QUITTING

**Comment by lgagne413** [comment]
Maybe an error catch add is all that is needed?

**Comment by deschman** [comment]
I would like to keep multithreading as the default in order to keep other tasks down the line as quick as possible. I believe I can have the threads catch this error and systematically wait until it is no longer busy. If not, I will probably have the program test whether the connection can handle multiple threads in advance and adjust itself as needed. I will try to push this with the next patch.

**Comment by deschman** [comment]
Still working on that error catch. What does your connection string look like for this?

**Comment by deschman** [comment]
I believe this can be resolved on SQL Server by enabling MARS as described [here](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/enabling-multiple-active-result-sets). 

However, the latest release 0.3.0, #4 , should prevent errors from occurring if the user is uncertain of their DB's ability to handle multithreading.
